# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mytun < Formula
  desc "MyTun.net - Expose any Port securely on internet"
  homepage "https://dashboard.mytun.net/"
  version "1.3.32"
  license "BSD 3-Clause License"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mytunnet/homebew-mytun/releases/download/v1.3.32/mytun_1.3.32_darwin_amd64.tar.gz"
    sha256 "69cd5d945cac49e454ae357532b9bf08da59e09f14f79fbef79f3223cd8a112b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/mytunnet/homebew-mytun/releases/download/v1.3.32/mytun_1.3.32_darwin_arm64.tar.gz"
    sha256 "fbe23efad7b0418349a44637391824d0a706c48a4e6b88c1e1d431f712863c70"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mytunnet/homebew-mytun/releases/download/v1.3.32/mytun_1.3.32_linux_amd64.tar.gz"
    sha256 "31b8dd15253e552efc5c1cf4c66887248b75b4589caf1787e15c8e920a704cc8"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/mytunnet/homebew-mytun/releases/download/v1.3.32/mytun_1.3.32_linux_arm.tar.gz"
    sha256 "834f30a0153ff2f7586da1501f9ca3202c528be97d589d86c182a15bb11498ce"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mytunnet/homebew-mytun/releases/download/v1.3.32/mytun_1.3.32_linux_arm64.tar.gz"
    sha256 "345360a6963583b9656c8b93cc14b8aa353fc110dc1b37c34c8d05ff6abef344"
  end

  def install
    bin.install "mytun"
  end

  def caveats; <<~EOS
    Usage: mytun YOUR_DEVICE_TOKEN
  EOS
  end
end
